// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApWYePpNFwwkpKNfe8wBjrcgcvYkVFmiI',
    appId: '1:982731246537:web:33adacd29c09bd572cf618',
    messagingSenderId: '982731246537',
    projectId: 'wishperlog',
    authDomain: 'wishperlog.firebaseapp.com',
    storageBucket: 'wishperlog.firebasestorage.app',
    measurementId: 'G-Z5XJT41VDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-0jX3pPJ-8iBDMlSW1W19ih_XkqtqH4E',
    appId: '1:982731246537:android:bff1e21915bd4c632cf618',
    messagingSenderId: '982731246537',
    projectId: 'wishperlog',
    storageBucket: 'wishperlog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGeq1oyfJaEBXgJRqOuEMTmJzo6IA7dkM',
    appId: '1:982731246537:ios:35dcd639c15b41aa2cf618',
    messagingSenderId: '982731246537',
    projectId: 'wishperlog',
    storageBucket: 'wishperlog.firebasestorage.app',
    iosClientId: '982731246537-ds47rpj0jsvqqoo62ej105n5i0l12u7k.apps.googleusercontent.com',
    iosBundleId: 'com.adarshkumarverma.wishperlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGeq1oyfJaEBXgJRqOuEMTmJzo6IA7dkM',
    appId: '1:982731246537:ios:35dcd639c15b41aa2cf618',
    messagingSenderId: '982731246537',
    projectId: 'wishperlog',
    storageBucket: 'wishperlog.firebasestorage.app',
    iosClientId: '982731246537-ds47rpj0jsvqqoo62ej105n5i0l12u7k.apps.googleusercontent.com',
    iosBundleId: 'com.adarshkumarverma.wishperlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApWYePpNFwwkpKNfe8wBjrcgcvYkVFmiI',
    appId: '1:982731246537:web:7745bf16f7cb93822cf618',
    messagingSenderId: '982731246537',
    projectId: 'wishperlog',
    authDomain: 'wishperlog.firebaseapp.com',
    storageBucket: 'wishperlog.firebasestorage.app',
    measurementId: 'G-3XSDF18KE6',
  );
}
